name: xeus-lite-wasm
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
  - dive
dependencies:
  - xeus-python
  - xeus-lua
  - xeus-sqlite
  - divewidgets
  - numpy
  - pandas
  - scikit-learn